---
- hosts: all
  become: yes
  vars:
    ansible_remote_tmp: /tmp/.ansible/tmp
  tasks:
    - name: Ensure temp directory exists
      file:
        path: /tmp/.ansible/tmp
        state: directory
        mode: '1777'
  roles:
    - nginx
