name: Test Ansible Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start infrastructure
        run: docker-compose up -d target

      - name: Wait for systemd initialization
        run: sleep 20

      - name: Run Ansible playbook
        run: |
          docker-compose build control
          docker-compose run control ansible-playbook \
            -i 'ansible-target,' \
            --connection=docker \
            playbook.yml

      - name: Verify NGINX installation
        run: docker exec ansible-target nginx -v

      - name: Test HTTP response
        run: docker exec ansible-target curl -sI http://localhost | grep "200 OK"
