name: Test Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker container
      run: docker-compose up -d

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i "localhost," -c local playbook.yml

    - name: Verify NGINX installation
      run: |
        docker exec ansible_test systemctl is-active nginx
        docker exec ansible_test curl -s -o /dev/null -w "%{http_code}" http://localhost | grep 200

    - name: Clean up
      run: docker-compose down
